apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickup
  labels:
    app: pickup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickup
  template:
    metadata:
      labels:
        app: pickup
    spec:
      containers:
        - name: pickup
          image: 936103362868.dkr.ecr.eu-central-1.amazonaws.com/pickup:v7
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m         